# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
#code here
# Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,12,12])
arr2 = arr1.reshape(3,4)
print(arr1)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 12 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 12 12]]


In [ ]:
#Concatenate two NumPy arrays horizontally and vertically.
import numpy as np

arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(11,21,(3,4))

horizontal = np.concatenate([arr1,arr2],axis=1)
vertical = np.concatenate([arr1,arr2],axis=0)

print("Horizontal: \n",horizontal)
print("Vertical: \n",vertical)

Horizontal: 
 [[ 2  4  3  9 14 16 14 19]
 [ 8  1  2  5 13 13 18 16]
 [ 9  2  9  6 18 17 14 18]]
Vertical: 
 [[ 2  4  3  9]
 [ 8  1  2  5]
 [ 9  2  9  6]
 [14 16 14 19]
 [13 13 18 16]
 [18 17 14 18]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
#code here

def classify_emails(emails):

    important = ["urgent", "important", "action"]
    promotion = ["discount", "offer"]
    spam = ["lottery", "free", "prize"]

    imp_email = []
    promo_email = []
    spam_e = []

    for e in emails:
        e_lower = e.lower()
        tokens = e_lower.split()
        for token in tokens:
            if token in important:
                imp_email.append(e)

            elif token in promotion:
                promo_email.append(e)

            elif token in spam:
                spam_e.append(e)


    return spam_e, imp_email, promo_email



Email_list = [
              "Urgent Your action required for biometric verification",
              "Important meeting arranged tomorrow",
              "offer on selected products upto",
              "discount available on J. dresses",
              "Yay! you won free hotdog"
]

spamm , important , promo = classify_emails(Email_list)

print("important: ")
for imp in important:
    print(imp)

print('Promotion Email: ')
for p in promo:
    print(p)

print("Spam: ")
for sp in spamm:
    print(sp)


important: 
Urgent Your action required for biometric verification
Urgent Your action required for biometric verification
Important meeting arranged tomorrow
Promotion Email: 
offer on selected products upto
discount available on J. dresses
Spam: 
Yay! you won free hotdog


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
#code here
#code here

content = {
    "apple": "manzana",
    "hello": "hola",
    "how are you": "Cómo estás",
    "what is you name": "cómo te llamas",
    "goodbye": "adiós",
    "car": "coche"
}

def Translator(word):
    if word in content:
        return content[word]
    else:
        return None


while True:

    word = input("Enter a word type 'exit' to quit: ").lower()
    if word == 'exit':
        break
    translate = Translator(word)
    if translate:
        print("The Spanish translation of '{}' is '{}'.".format(word, translate))
    else:
        print("Translation not available for '{}'.".format(word))


Enter a word type 'exit' to quit: car
The Spanish translation of 'car' is 'coche'.
Enter a word type 'exit' to quit: exit


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))


In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv', delimiter=',')
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [3]:
# Total global sales in the dataset.
df['Global_Sales'].sum()

8920.44

In [11]:
# the game with the highest global sales.

df[df['Global_Sales'] == df['Global_Sales'].max()]

Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74

In [12]:
# average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).

df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()

NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [14]:
# Find the top 5 most popular game genres based on global sales.

df.groupby('Genre')['Global_Sales'].sum().nlargest(5)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [18]:
# Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).

print(df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum())

df.groupby('Genre')['NA_Sales'].sum().nlargest(1)



              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


Genre
Action    877.83
Name: NA_Sales, dtype: float64

In [19]:
# Display last 10 rows.

df.tail(10)


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [20]:
# Determine the top 3 gaming platforms with the highest global sales.

df.groupby('Platform')['Global_Sales'].sum().nlargest(3)


Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [21]:
# Calculate the market share (percentage of global sales) for each genre.

total_global_sales = df['Global_Sales'].sum()
genre_sales = df.groupby('Genre')['Global_Sales'].sum()
market_share = (genre_sales / total_global_sales) * 100
market_share


Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [22]:
# Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

df['NA_Sales'].corr(df['EU_Sales'])

0.7677267483702562